namespace System.Xml.Xsl.Runtime;

internal enum NumberingSequence
{
	Nil = -1,
	FirstDecimal = 0,
	Arabic = FirstDecimal,
	DArabic = 1,
	Hindi3 = 2,
	Thai2 = 3,
	FEDecimal = 4,
	KorDbNum1 = 5,
	LastNum = KorDbNum1,
	FirstAlpha = 6,
	UCLetter = FirstAlpha,
	LCLetter = 7,
	UCRus = 8,
	LCRus = 9,
	Thai1 = 10,
	Hindi1 = 11,
	Hindi2 = 12,
	Aiueo = 13,
	DAiueo = 14,
	Iroha = 15,
	DIroha = 16,
	DChosung = 17,
	Ganada = 18,
	ArabicScript = 19,
	LastAlpha = ArabicScript,
	FirstSpecial = 20,
	UCRoman = FirstSpecial,
	LCRoman = 21,
	Hebrew = 22,
	DbNum3 = 23,
	ChnCmplx = 24,
	KorDbNum3 = 25,
	Zodiac1 = 26,
	Zodiac2 = 27,
	Zodiac3 = 28,
	LastSpecial = Zodiac3
}
