namespace System.Runtime.CompilerServices;

[Flags]
internal enum CorInfoContinuationFlags
{
	CORINFO_CONTINUATION_RESULT_IN_GCDATA = 1,
	CORINFO_CONTINUATION_NEEDS_EXCEPTION = 2,
	CORINFO_CONTINUATION_OSR_IL_OFFSET_IN_DATA = 4,
	CORINFO_CONTINUATION_CONTINUE_ON_THREAD_POOL = 8,
	CORINFO_CONTINUATION_CONTINUE_ON_CAPTURED_SYNCHRONIZATION_CONTEXT = 0x10,
	CORINFO_CONTINUATION_CONTINUE_ON_CAPTURED_TASK_SCHEDULER = 0x20
}
