<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>ApocZ</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFramework>net481</TargetFramework>
		<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU</Platforms>
		<OutputType>WinExe</OutputType>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Content-References\Contents.csproj">
			<Private>True</Private>
			<CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="DataCompressor">
			<HintPath>DataCompressor.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="DataContent">
			<HintPath>DataContent.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="EGEngine">
			<HintPath>EGEngine.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="MaxscriptDefinesXbox360">
			<HintPath>MaxscriptDefinesXbox360.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="PropModel">
			<HintPath>PropModel.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="SkinnedModel">
			<HintPath>SkinnedModel.dll</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>