<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Microsoft.Xna.Framework.Avatars.FNA</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.XboxLive.Avatars.Mathlib">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.XboxLive.Avatars.Mathlib.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.XboxLive.Avatars">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.XboxLive.Avatars.dll</HintPath>
    </Reference>
    <Reference Include="FNA">
      <HintPath>DLC\Avatar Farm Online Complete\Game\FNA.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.Xna.Framework.GamerServices">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.Xna.Framework.GamerServices.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>