<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Microsoft.Xna.Framework.Storage</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="FNA">
      <HintPath>DLC\Avatar Farm Online Complete\Game\FNA.dll</HintPath>
    </Reference>
    <Reference Include="XnaToFna">
      <HintPath>DLC\Avatar Farm Online Complete\Game\XnaToFna.exe</HintPath>
    </Reference>
  </ItemGroup>
</Project>