<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Microsoft.XboxLive.Avatars</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Xml" />
    <Reference Include="Microsoft.XboxLive.Avatars.Mathlib">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.XboxLive.Avatars.Mathlib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>