<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>sgMotionPlugin</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Microsoft.Xna.Framework.RuntimeProfile" />
    <EmbeddedResource Include="Microsoft.Xna.Framework.RuntimeProfile" LogicalName="Microsoft.Xna.Framework.RuntimeProfile" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="SynapseGaming-SunBurn-Indie">
      <HintPath>DLC\decompiled\Dead Sea (World) (XBLIG)\SynapseGaming-SunBurn-Indie.dll</HintPath>
    </Reference>
    <Reference Include="sgMotion">
      <HintPath>DLC\decompiled\Dead Sea (World) (XBLIG)\sgMotion.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework.Game" />
    <Reference Include="Microsoft.Xna.Framework.Graphics" />
    <Reference Include="Microsoft.Xna.Framework" />
  </ItemGroup>
</Project>