<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.Security</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Security.Cryptography.Pkcs">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.Security.Cryptography.Pkcs.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Cryptography.ProtectedData">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.Security.Cryptography.ProtectedData.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Extensions">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.Windows.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Cryptography.Xml">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.Security.Cryptography.Xml.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Permissions">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.Security.Permissions.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>