<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.Core</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Diagnostics.EventLog">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.Diagnostics.EventLog.dll</HintPath>
    </Reference>
    <Reference Include="System.Diagnostics.PerformanceCounter">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.Diagnostics.PerformanceCounter.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>