<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WindowsBase</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.IO.Packaging">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.IO.Packaging.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Permissions">
      <HintPath>..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\10.0.3\System.Security.Permissions.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>