<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XBLIGGameUtils</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationCelebrate.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationClap.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleAngry.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleConfused.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleCry.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleCheckNails.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleFixShoe.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleLookAround.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleShiftWeight.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleLaugh.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleShocked.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationFemaleYawn.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleAngry.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleConfused.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleCry.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleIdleCheckHand.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleIdleLookAround.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleIdleShiftWeight.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleIdleStretch.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleLaugh.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleSurprised.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationMaleYawn.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationStand0.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationStand1.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationStand2.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationStand3.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationStand4.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationStand5.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationStand6.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationStand7.bin" />
    <None Remove="AvatarFarmCompat.AnimationResources.AnimationWave.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationCelebrate.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationCelebrate.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationClap.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationClap.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleAngry.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleAngry.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleConfused.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleConfused.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleCry.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleCry.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleCheckNails.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleCheckNails.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleFixShoe.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleFixShoe.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleLookAround.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleLookAround.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleShiftWeight.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleIdleShiftWeight.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleLaugh.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleLaugh.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleShocked.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleShocked.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationFemaleYawn.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationFemaleYawn.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleAngry.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleAngry.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleConfused.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleConfused.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleCry.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleCry.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleIdleCheckHand.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleIdleCheckHand.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleIdleLookAround.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleIdleLookAround.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleIdleShiftWeight.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleIdleShiftWeight.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleIdleStretch.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleIdleStretch.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleLaugh.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleLaugh.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleSurprised.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleSurprised.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationMaleYawn.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationMaleYawn.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationStand0.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationStand0.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationStand1.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationStand1.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationStand2.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationStand2.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationStand3.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationStand3.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationStand4.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationStand4.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationStand5.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationStand5.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationStand6.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationStand6.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationStand7.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationStand7.bin" />
    <EmbeddedResource Include="AvatarFarmCompat.AnimationResources.AnimationWave.bin" LogicalName="AvatarFarmCompat.AnimationResources.AnimationWave.bin" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Xna.Framework.Avatar">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.Xna.Framework.Avatar.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework.Avatars.FNA">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.Xna.Framework.Avatars.FNA.dll</HintPath>
    </Reference>
    <Reference Include="FNA">
      <HintPath>DLC\Avatar Farm Online Complete\Game\FNA.dll</HintPath>
    </Reference>
    <Reference Include="QuasarGameUtils">
      <HintPath>DLC\Avatar Farm Online Complete\Game\QuasarGameUtils.dll</HintPath>
    </Reference>
    <Reference Include="Quasar">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Quasar.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework.GamerServices">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.Xna.Framework.GamerServices.dll</HintPath>
    </Reference>
    <Reference Include="XnaToFna">
      <HintPath>DLC\Avatar Farm Online Complete\Game\XnaToFna.exe</HintPath>
    </Reference>
    <Reference Include="Microsoft.XboxLive.Avatars">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.XboxLive.Avatars.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.XboxLive.Avatars.Editing">
      <HintPath>DLC\Avatar Farm Online Complete\Game\Microsoft.XboxLive.Avatars.Editing.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>