<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Elite.Core</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net481</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="gamethumbnail.png" />
    <None Remove="Microsoft.Xna.Framework.RuntimeProfile" />
    <EmbeddedResource Include="gamethumbnail.png" LogicalName="gamethumbnail.png" />
    <EmbeddedResource Include="Microsoft.Xna.Framework.RuntimeProfile" LogicalName="Microsoft.Xna.Framework.RuntimeProfile" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Content-References\Contents.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Elite.Core.Shared">
      <HintPath>..\..\extracted\Jet Set Willy 360 (World) (XBLIG)\584E07D1\Elite.Core.Shared.dll</HintPath>
    </Reference>
    <Reference Include="ZXBox.Core">
      <HintPath>..\..\extracted\Jet Set Willy 360 (World) (XBLIG)\584E07D1\ZXBox.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>