<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZP2KX</AssemblyName>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <TargetFramework>net5.0-windows7.0</TargetFramework>
	  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <Platforms>AnyCPU;x86;x64</Platforms>
	  <OutputType>WinExe</OutputType>
	  <LangVersion>14.0</LangVersion>
	  <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	  <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
	  <ProjectReference Include="..\..\Content-References\FNA.Contents.csproj" />
  </ItemGroup>
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Microsoft.Xna.Framework.RuntimeProfile" />
    <EmbeddedResource Include="Microsoft.Xna.Framework.RuntimeProfile" LogicalName="Microsoft.Xna.Framework.RuntimeProfile" />
  </ItemGroup>
</Project>