<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Manic Miner 360</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
		<PlatformTarget>x86</PlatformTarget>
		<RootNamespace />
		<OutputType>WinExe</OutputType>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
	<PropertyGroup>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationIcon>app.ico</ApplicationIcon>
		<RootNamespace />
		<StartupObject>Manic_Miner_360.Program</StartupObject>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="gamethumbnail.png" />
		<None Remove="Microsoft.Xna.Framework.RuntimeProfile" />
		<EmbeddedResource Include="gamethumbnail.png" LogicalName="gamethumbnail.png" />
		<EmbeddedResource Include="Microsoft.Xna.Framework.RuntimeProfile" LogicalName="Microsoft.Xna.Framework.RuntimeProfile" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="ZXBox.Core">
			<HintPath>..\..\extracted\Manic Miner 360 (World) (XBLIG)\584E07D1\ZXBox.Core.dll</HintPath>
		</Reference>
		<Reference Include="System.Core">
			<HintPath>C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\System.Core.dll</HintPath>
		</Reference>
		<ProjectReference Include="..\..\Content-References\FNA.Contents.csproj" />
	</ItemGroup>
</Project>