<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Manic Miner 360</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PlatformTarget>x64</PlatformTarget>
		<OutputType>WinExe</OutputType>
		<Platforms>x86;x64</Platforms>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
		<ApplicationIcon>app.ico</ApplicationIcon>
		<RootNamespace>Manic_Miner_360</RootNamespace>
		<StartupObject>Manic_Miner_360.Program</StartupObject>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="gamethumbnail.png" />
		<None Remove="Microsoft.Xna.Framework.RuntimeProfile" />
		<EmbeddedResource Include="gamethumbnail.png" LogicalName="gamethumbnail.png" />
		<EmbeddedResource Include="Microsoft.Xna.Framework.RuntimeProfile" LogicalName="Microsoft.Xna.Framework.RuntimeProfile" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="ZXBox.Core">
			<HintPath>..\..\extracted\Manic Miner 360 (World) (XBLIG)\584E07D1\ZXBox.Core.dll</HintPath>
		</Reference>
		<ProjectReference Include="..\..\Content-References\FNA.Contents.csproj">
			<Private>True</Private>
			<CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
	  <None Update="48.rom">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="manic_cheat.z80">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="manic_normal.z80">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="manic_trial.z80">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>