<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SupernovaStorm</AssemblyName>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <TargetFramework>net481</TargetFramework>
	  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <OutputType>WinExe</OutputType>
	  <LangVersion>14.0</LangVersion>
	  <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	  <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
	  <ProjectReference Include="..\..\Content-References\Contents.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Microsoft.Xna.Framework.RuntimeProfile" />
    <EmbeddedResource Include="Microsoft.Xna.Framework.RuntimeProfile" LogicalName="Microsoft.Xna.Framework.RuntimeProfile" />
  </ItemGroup>
</Project>