namespace System.Transactions.DtcProxyShim;

[Flags]
internal enum OletxTransactionIsoFlags
{
	ISOFLAG_NONE = 0,
	ISOFLAG_RETAIN_COMMIT_DC = 1,
	ISOFLAG_RETAIN_COMMIT = 2,
	ISOFLAG_RETAIN_COMMIT_NO = ISOFLAG_RETAIN_COMMIT_DC | ISOFLAG_RETAIN_COMMIT,
	ISOFLAG_RETAIN_ABORT_DC = 4,
	ISOFLAG_RETAIN_ABORT = 8,
	ISOFLAG_RETAIN_ABORT_NO = ISOFLAG_RETAIN_ABORT_DC | ISOFLAG_RETAIN_ABORT,
	ISOFLAG_RETAIN_DONTCARE = ISOFLAG_RETAIN_COMMIT_DC | ISOFLAG_RETAIN_ABORT_DC,
	ISOFLAG_RETAIN_BOTH = ISOFLAG_RETAIN_COMMIT | ISOFLAG_RETAIN_ABORT,
	ISOFLAG_RETAIN_NONE = ISOFLAG_RETAIN_COMMIT_NO | ISOFLAG_RETAIN_ABORT_NO,
	ISOFLAG_OPTIMISTIC = 0x10,
	ISOFLAG_READONLY = 0x20
}
