namespace System.Transactions.DtcProxyShim;

internal enum OletxTransactionIsolationLevel
{
	ISOLATIONLEVEL_UNSPECIFIED = -1,
	ISOLATIONLEVEL_CHAOS = 16,
	ISOLATIONLEVEL_READUNCOMMITTED = 256,
	ISOLATIONLEVEL_BROWSE = ISOLATIONLEVEL_READUNCOMMITTED,
	ISOLATIONLEVEL_CURSORSTABILITY = 4096,
	ISOLATIONLEVEL_READCOMMITTED = ISOLATIONLEVEL_CURSORSTABILITY,
	ISOLATIONLEVEL_REPEATABLEREAD = 65536,
	ISOLATIONLEVEL_SERIALIZABLE = 1048576,
	ISOLATIONLEVEL_ISOLATED = ISOLATIONLEVEL_SERIALIZABLE
}
