<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>3D Infinity (World) (XBLIG)</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>WinExe</OutputType>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
		<EnableDefaultEmbeddedResourceItems>False</EnableDefaultEmbeddedResourceItems>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x86;x64</Platforms>
		<RootNameSpace>3D Infinity (World) (XBLIG)</RootNameSpace>
		<StartupObject>3D Infinity (World) (XBLIG).Program</StartupObject>
		<ApplicationIcon>gamethumbnail.png</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Content-References\FNA.Contents.csproj">
			<Private>True</Private>
			<CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="InfinityLibrary">
			<HintPath>InfinityLibrary.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="ParticleLibrary">
			<HintPath>ParticleLibrary.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="XSIXNARuntime">
			<HintPath>XSIXNARuntime.dll</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Include="ja/Infinity.resources.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Infinity.Messages.UIMessage.resx" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>