namespace System.Text.RegularExpressions;

internal enum RegexNodeKind : byte
{
	Unknown = 0,
	One = 9,
	Notone = 10,
	Set = 11,
	Multi = 12,
	Oneloop = 3,
	Notoneloop = 4,
	Setloop = 5,
	Onelazy = 6,
	Notonelazy = 7,
	Setlazy = 8,
	Oneloopatomic = 43,
	Notoneloopatomic = 44,
	Setloopatomic = 45,
	Backreference = 13,
	Bol = 14,
	Eol = 15,
	Boundary = 16,
	NonBoundary = 17,
	ECMABoundary = 41,
	NonECMABoundary = 42,
	Beginning = 18,
	Start = 19,
	EndZ = 20,
	End = 21,
	UpdateBumpalong = 46,
	Nothing = 22,
	Empty = 23,
	Alternate = 24,
	Concatenate = 25,
	Loop = 26,
	Lazyloop = 27,
	Capture = 28,
	Group = 29,
	Atomic = 32,
	PositiveLookaround = 30,
	NegativeLookaround = 31,
	BackreferenceConditional = 33,
	ExpressionConditional = 34
}
