<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Common</AssemblyName>
	  <TargetFramework>net5.0-windows7.0</TargetFramework>
	  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
	  <TargetFramework>net5.0-windows7.0</TargetFramework>
	  <PlatformTarget>x86</PlatformTarget>
	  <LangVersion>14.0</LangVersion>
	  <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	  <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	  <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Content-References\FNA.Contents.csproj" />
  </ItemGroup>
</Project>