<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Decay: The Mare - Episode 1</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>WinExe</OutputType>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
		<EnableDefaultEmbeddedResourceItems>False</EnableDefaultEmbeddedResourceItems>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x86;x64</Platforms>
		<RootNameSpace>Decay: The Mare - Episode 1</RootNameSpace>
		<StartupObject>Decay: The Mare - Episode 1.Program</StartupObject>
		<ApplicationIcon>gamethumbnail.png</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Content-References\FNA.Contents.csproj">
			<Private>True</Private>
			<CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Core">
			<HintPath>584E07D1/Core.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="SGSCore">
			<HintPath>584E07D1/SGSCore.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="SGSXML">
			<HintPath>584E07D1/SGSXML.dll</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup />
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>