using System;
using System.Collections.Generic;
using BEPUphysics.BroadPhaseEntries;
using BEPUphysics.BroadPhaseSystems;
using BEPUphysics.CollisionRuleManagement;
using BEPUphysics.DataStructures;
using BEPUphysics.NarrowPhaseSystems.Pairs;
using BEPUphysics.SolverSystems;
using BEPUphysics.Threading;

namespace BEPUphysics.NarrowPhaseSystems;

/// <summary>
///  Manages and constructs pair handlers from broad phase overlaps.
/// </summary>
public class NarrowPhase : MultithreadedProcessingStage
{
	private RawList<BroadPhaseOverlap> broadPhaseOverlaps;

	private Dictionary<BroadPhaseOverlap, NarrowPhasePair> overlapMapping = new Dictionary<BroadPhaseOverlap, NarrowPhasePair>();

	private RawList<NarrowPhasePair> narrowPhasePairs = new RawList<NarrowPhasePair>();

	private ConcurrentDeque<NarrowPhasePair> newNarrowPhasePairs = new ConcurrentDeque<NarrowPhasePair>();

	private Action<int> updateBroadPhaseOverlapDelegate;

	private ConcurrentDeque<SolverUpdateableChange> solverUpdateableChanges = new ConcurrentDeque<SolverUpdateableChange>();

	/// <summary>
	///  Gets or sets the list of broad phase overlaps used by the narrow phase to manage pairs.
	/// </summary>
	public RawList<BroadPhaseOverlap> BroadPhaseOverlaps
	{
		get
		{
			return broadPhaseOverlaps;
		}
		set
		{
			broadPhaseOverlaps = value;
		}
	}

	/// <summary>
	///  Gets the list of Pairs managed by the narrow phase.
	/// </summary>
	public ReadOnlyList<NarrowPhasePair> Pairs => new ReadOnlyList<NarrowPhasePair>(narrowPhasePairs);

	/// <summary>
	///  Gets or sets the time step settings used by the narrow phase.
	/// </summary>
	public TimeStepSettings TimeStepSettings { get; set; }

	/// <summary>
	/// Gets or sets the solver into which the narrow phase will put solver updateables generated by narrow phase pairs.
	/// </summary>
	public Solver Solver { get; set; }

	/// <summary>
	/// If true, solver updateables added and removed from narrow phase pairs will be added directly to the solver
	/// without any synchronization or queueing.
	/// </summary>
	private bool ApplySolverUpdateableChangesDirectly { get; set; }

	/// <summary>
	///  Fires when the narrow phase creates a pair.
	/// </summary>
	public event Action<NarrowPhasePair> CreatingPair;

	/// <summary>
	///  Fires when the narrow phase removes a pair.
	/// </summary>
	public event Action<NarrowPhasePair> RemovingPair;

	/// <summary>
	///  Constructs a new narrow phase.
	/// </summary>
	/// <param name="timeStepSettings">Time step settings used by the narrow phase.</param>
	public NarrowPhase(TimeStepSettings timeStepSettings)
	{
		TimeStepSettings = timeStepSettings;
		updateBroadPhaseOverlapDelegate = UpdateBroadPhaseOverlap;
		Enabled = true;
	}

	/// <summary>
	///  Constructs a new narrow phase.
	/// </summary>
	/// <param name="timeStepSettings">Time step settings used by the narrow phase.</param>
	///  <param name="overlaps">Overlaps list used by the narrow phase to create pairs.</param>
	public NarrowPhase(TimeStepSettings timeStepSettings, RawList<BroadPhaseOverlap> overlaps)
		: this(timeStepSettings)
	{
		broadPhaseOverlaps = overlaps;
	}

	/// <summary>
	///  Constructs a new narrow phase.
	/// </summary>
	/// <param name="timeStepSettings">Time step settings used by the narrow phase.</param>
	///  <param name="overlaps">Overlaps list used by the narrow phase to create pairs.</param>
	///  <param name="threadManager">Thread manager used by the narrow phase.</param>
	public NarrowPhase(TimeStepSettings timeStepSettings, RawList<BroadPhaseOverlap> overlaps, IThreadManager threadManager)
		: this(timeStepSettings, overlaps)
	{
		base.ThreadManager = threadManager;
		base.AllowMultithreading = true;
	}

	private void UpdateBroadPhaseOverlap(int i)
	{
		BroadPhaseOverlap pair = broadPhaseOverlaps.Elements[i];
		if (pair.collisionRule >= CollisionRule.NoNarrowPhasePair)
		{
			return;
		}
		if (!overlapMapping.TryGetValue(pair, out var value))
		{
			value = NarrowPhaseHelper.GetPairHandler(ref pair);
			if (value != null)
			{
				value.NarrowPhase = this;
				newNarrowPhasePairs.Enqueue(value);
			}
		}
		if (value != null)
		{
			value.CollisionRule = pair.collisionRule;
			if (value.BroadPhaseOverlap.collisionRule < CollisionRule.NoNarrowPhaseUpdate)
			{
				value.UpdateCollision(TimeStepSettings.TimeStepDuration);
			}
			value.NeedsUpdate = false;
		}
	}

	protected override void UpdateMultithreaded()
	{
		base.ThreadManager.ForLoop(0, broadPhaseOverlaps.Count, updateBroadPhaseOverlapDelegate);
		AddNewNarrowPhaseObjects();
		FlushGeneratedSolverUpdateables();
		RemoveStaleOverlaps();
	}

	protected override void UpdateSingleThreaded()
	{
		int count = broadPhaseOverlaps.Count;
		for (int i = 0; i < count; i++)
		{
			UpdateBroadPhaseOverlap(i);
		}
		AddNewNarrowPhaseObjects();
		FlushGeneratedSolverUpdateables();
		RemoveStaleOverlaps();
	}

	private void RemoveStaleOverlaps()
	{
		ApplySolverUpdateableChangesDirectly = true;
		for (int num = narrowPhasePairs.count - 1; num >= 0; num--)
		{
			NarrowPhasePair narrowPhasePair = narrowPhasePairs.Elements[num];
			if (narrowPhasePair.NeedsUpdate && (narrowPhasePair.broadPhaseOverlap.entryA.IsActive || narrowPhasePair.broadPhaseOverlap.entryB.IsActive || narrowPhasePair.broadPhaseOverlap.entryA.BroadPhase == null || narrowPhasePair.broadPhaseOverlap.entryB.BroadPhase == null))
			{
				if (RemovingPair != null)
				{
					RemovingPair(narrowPhasePair);
				}
				narrowPhasePairs.FastRemoveAt(num);
				overlapMapping.Remove(narrowPhasePair.BroadPhaseOverlap);
				narrowPhasePair.CleanUp();
				narrowPhasePair.Factory.GiveBack(narrowPhasePair);
			}
			else
			{
				narrowPhasePair.NeedsUpdate = true;
			}
		}
		ApplySolverUpdateableChangesDirectly = false;
	}

	private void AddNewNarrowPhaseObjects()
	{
		NarrowPhasePair item;
		while (newNarrowPhasePairs.TryUnsafeDequeueFirst(out item))
		{
			narrowPhasePairs.Add(item);
			OnCreatePair(item);
		}
	}

	/// <summary>
	///  Gets the pair between two broad phase entries, if any.
	/// </summary>
	/// <param name="entryA">First entry in the pair.</param>
	/// <param name="entryB">Second entry in the pair.</param>
	/// <returns>The pair if it exists, null otherwise.</returns>
	public NarrowPhasePair GetPair(BroadPhaseEntry entryA, BroadPhaseEntry entryB)
	{
		overlapMapping.TryGetValue(new BroadPhaseOverlap(entryA, entryB), out var value);
		return value;
	}

	protected void OnCreatePair(NarrowPhasePair pair)
	{
		overlapMapping.Add(pair.BroadPhaseOverlap, pair);
		pair.OnAddedToNarrowPhase();
		if (CreatingPair != null)
		{
			CreatingPair(pair);
		}
	}

	/// <summary>
	///  Enqueues a solver updateable created by some pair for flushing into the solver later.
	/// </summary>
	/// <param name="addedItem">Updateable to add.</param>
	public void NotifyUpdateableAdded(SolverUpdateable addedItem)
	{
		if (ApplySolverUpdateableChangesDirectly)
		{
			Solver.Add(addedItem);
		}
		else
		{
			solverUpdateableChanges.Enqueue(new SolverUpdateableChange(shouldAdd: true, addedItem));
		}
	}

	/// <summary>
	///  Enqueues a solver updateable removed by some pair for flushing into the solver later.
	/// </summary>
	/// <param name="removedItem">Solver updateable to remove.</param>
	public void NotifyUpdateableRemoved(SolverUpdateable removedItem)
	{
		if (ApplySolverUpdateableChangesDirectly)
		{
			Solver.Remove(removedItem);
		}
		else
		{
			solverUpdateableChanges.Enqueue(new SolverUpdateableChange(shouldAdd: false, removedItem));
		}
	}

	/// <summary>
	/// Flushes the new solver updateables into the solver.
	/// They are 'flux' updateables, so this uses the solver's flux add method.
	/// </summary>
	public void FlushGeneratedSolverUpdateables()
	{
		SolverUpdateableChange item;
		while (solverUpdateableChanges.TryUnsafeDequeueFirst(out item))
		{
			if (item.ShouldAdd)
			{
				if (item.Item.solver == null)
				{
					Solver.Add(item.Item);
				}
			}
			else if (item.Item.solver != null)
			{
				Solver.Remove(item.Item);
			}
		}
	}
}
