namespace Microsoft.CSharp.RuntimeBinder.Semantics;

internal enum ACCESS
{
	ACC_UNKNOWN,
	ACC_PRIVATE,
	ACC_INTERNAL_AND_PROTECTED,
	ACC_INTERNAL,
	ACC_PROTECTED,
	ACC_INTERNALPROTECTED,
	ACC_PUBLIC
}
