using System;
using System.ComponentModel;

namespace Microsoft.CSharp.RuntimeBinder;

/// <summary>Represents information about C# dynamic operations that are specific to particular arguments at a call site. Instances of this class are generated by the C# compiler.</summary>
[Flags]
[EditorBrowsable(EditorBrowsableState.Never)]
public enum CSharpArgumentInfoFlags
{
	/// <summary>No additional information to represent.</summary>
	None = 0,
	/// <summary>The argument's compile-time type should be considered during binding.</summary>
	UseCompileTimeType = 1,
	/// <summary>The argument is a constant.</summary>
	Constant = 2,
	/// <summary>The argument is a named argument.</summary>
	NamedArgument = 4,
	/// <summary>The argument is passed to a ref parameter.</summary>
	IsRef = 8,
	/// <summary>The argument is passed to an out parameter.</summary>
	IsOut = 0x10,
	/// <summary>The argument is a <see cref="T:System.Type" /> indicating an actual type name used in source. Used only for target objects in static calls.</summary>
	IsStaticType = 0x20
}
