using System.ComponentModel;

namespace Microsoft.CSharp.RuntimeBinder;

/// <summary>Represents information about C# dynamic operations that are specific to particular arguments at a call site. Instances of this class are generated by the C# compiler.</summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class CSharpArgumentInfo
{
	internal static readonly CSharpArgumentInfo None = new CSharpArgumentInfo(CSharpArgumentInfoFlags.None, null);

	internal CSharpArgumentInfoFlags Flags { get; }

	internal string Name { get; }

	internal bool UseCompileTimeType => (Flags & CSharpArgumentInfoFlags.UseCompileTimeType) != 0;

	internal bool LiteralConstant => (Flags & CSharpArgumentInfoFlags.Constant) != 0;

	internal bool NamedArgument => (Flags & CSharpArgumentInfoFlags.NamedArgument) != 0;

	internal bool IsByRefOrOut => (Flags & (CSharpArgumentInfoFlags.IsRef | CSharpArgumentInfoFlags.IsOut)) != 0;

	internal bool IsOut => (Flags & CSharpArgumentInfoFlags.IsOut) != 0;

	internal bool IsStaticType => (Flags & CSharpArgumentInfoFlags.IsStaticType) != 0;

	private CSharpArgumentInfo(CSharpArgumentInfoFlags flags, string name)
	{
		Flags = flags;
		Name = name;
	}

	/// <summary>Initializes a new instance of the <see cref="T:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo" /> class.</summary>
	/// <param name="flags">The flags for the argument.</param>
	/// <param name="name">The name of the argument, if named; otherwise null.</param>
	/// <returns>A new instance of the <see cref="T:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo" /> class.</returns>
	public static CSharpArgumentInfo Create(CSharpArgumentInfoFlags flags, string? name)
	{
		return new CSharpArgumentInfo(flags, name);
	}
}
