<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Common</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
				<TargetFramework>net481</TargetFramework>
		<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU</Platforms>
		<OutputType>WinExe</OutputType>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
		<StartupObject>Manic_Miner_360.Program</StartupObject>
		<StartupObject>Game.Program</StartupObject>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Content-References\Contents.csproj">
			<Private>True</Private>
			<CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
		</ProjectReference>
		<ProjectReference Include="..\..\Reference-Projects\Common\Common.csproj" />
		<ProjectReference Include="..\..\Reference-Projects\GKEngine\GKEngine.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Using Include="GKEngine.Entities.Range" Alias="Range" />
	</ItemGroup>
</Project>