namespace Microsoft.Quic;

internal enum QUIC_TLS_ALERT_CODES
{
	SUCCESS = 65535,
	UNEXPECTED_MESSAGE = 10,
	BAD_CERTIFICATE = 42,
	UNSUPPORTED_CERTIFICATE = 43,
	CERTIFICATE_REVOKED = 44,
	CERTIFICATE_EXPIRED = 45,
	CERTIFICATE_UNKNOWN = 46,
	ILLEGAL_PARAMETER = 47,
	UNKNOWN_CA = 48,
	ACCESS_DENIED = 49,
	INSUFFICIENT_SECURITY = 71,
	INTERNAL_ERROR = 80,
	USER_CANCELED = 90,
	CERTIFICATE_REQUIRED = 116,
	MAX = 255
}
