namespace Microsoft.Quic;

internal enum QUIC_CREDENTIAL_TYPE
{
	NONE,
	CERTIFICATE_HASH,
	CERTIFICATE_HASH_STORE,
	CERTIFICATE_CONTEXT,
	CERTIFICATE_FILE,
	CERTIFICATE_FILE_PROTECTED,
	CERTIFICATE_PKCS12
}
