<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>AircraftRC</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x86;x64</Platforms>
		<OutputType>WinExe</OutputType>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\Content-References\Contents.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="BEPUphysics">
	    <HintPath>BEPUphysics.dll</HintPath>
	  </Reference>
	  <Reference Include="DPSFXbox360">
	    <HintPath>DPSFXbox360.dll</HintPath>
	  </Reference>
	  <Reference Include="SynapseGaming-SunBurn-Indie">
	    <HintPath>SynapseGaming-SunBurn-Indie.dll</HintPath>
	  </Reference>
	</ItemGroup>
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>