<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Aircraft RC</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFramework>net481</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU</Platforms>
		<OutputType>WinExe</OutputType>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
		<EnableDefaultEmbeddedResourceItems>False</EnableDefaultEmbeddedResourceItems>
		<PlatformTarget>x86</PlatformTarget>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Content-References\FNA.Contents.csproj">
			<Private>True</Private>
			<CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="BEPUphysics">
			<HintPath>BEPUphysics.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="DPSFXbox360">
			<HintPath>DPSFXbox360.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="SynapseGaming-SunBurn-Indie">
			<HintPath>SynapseGaming-SunBurn-Indie.dll</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Include="es/AircraftRC.resources.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="fr/AircraftRC.resources.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="AircraftRC.Strings.fr.resx" />
		<EmbeddedResource Include="AircraftRC.Strings.resx" />
		<EmbeddedResource Include="DPSF.DPSFResources.resx" />
		<EmbeddedResource Include="SynapseGaming.LightingSystem.Effects.Resources-Xbox360.resx" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>