<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>27 Ball Funky Pool</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>WinExe</OutputType>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
		<EnableDefaultEmbeddedResourceItems>False</EnableDefaultEmbeddedResourceItems>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x86;x64</Platforms>
		<RootNameSpace>27 Ball Funky Pool</RootNameSpace>
		<StartupObject>27 Ball Funky Pool.Program</StartupObject>
		<ApplicationIcon>gamethumbnail.png</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Content-References\Contents.csproj">
			<Private>True</Private>
			<CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="LibMaximinus">
			<HintPath>LibMaximinus.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="MaximinusDataTypes">
			<HintPath>MaximinusDataTypes.dll</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup />
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>