using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks.Dataflow.Internal;

namespace System.Threading.Tasks.Dataflow;

/// <summary>Provides a dataflow block that batches a specified number of inputs of potentially differing types provided to one or more of its targets.</summary>
/// <typeparam name="T1">Specifies the type of data accepted by the block's first target.</typeparam>
/// <typeparam name="T2">Specifies the type of data accepted by the block's second target.</typeparam>
[DebuggerDisplay("{DebuggerDisplayContent,nq}")]
[DebuggerTypeProxy(typeof(BatchedJoinBlock<, >.DebugView))]
public sealed class BatchedJoinBlock<T1, T2> : IReceivableSourceBlock<Tuple<IList<T1>, IList<T2>>>, ISourceBlock<Tuple<IList<T1>, IList<T2>>>, IDataflowBlock, IDebuggerDisplay
{
	private sealed class DebugView
	{
		private readonly BatchedJoinBlock<T1, T2> _batchedJoinBlock;

		private readonly SourceCore<Tuple<IList<T1>, IList<T2>>>.DebuggingInformation _sourceDebuggingInformation;

		public IEnumerable<Tuple<IList<T1>, IList<T2>>> OutputQueue => _sourceDebuggingInformation.OutputQueue;

		public long BatchesCreated => _batchedJoinBlock._sharedResources._batchesCreated;

		public int RemainingItemsForBatch => _batchedJoinBlock._sharedResources._remainingItemsInBatch;

		public int BatchSize => _batchedJoinBlock._batchSize;

		public ITargetBlock<T1> Target1 => _batchedJoinBlock._target1;

		public ITargetBlock<T2> Target2 => _batchedJoinBlock._target2;

		public Task TaskForOutputProcessing => _sourceDebuggingInformation.TaskForOutputProcessing;

		public GroupingDataflowBlockOptions DataflowBlockOptions => (GroupingDataflowBlockOptions)_sourceDebuggingInformation.DataflowBlockOptions;

		public bool IsCompleted => _sourceDebuggingInformation.IsCompleted;

		public int Id => Common.GetBlockId(_batchedJoinBlock);

		public TargetRegistry<Tuple<IList<T1>, IList<T2>>> LinkedTargets => _sourceDebuggingInformation.LinkedTargets;

		public ITargetBlock<Tuple<IList<T1>, IList<T2>>> NextMessageReservedFor => _sourceDebuggingInformation.NextMessageReservedFor;

		public DebugView(BatchedJoinBlock<T1, T2> batchedJoinBlock)
		{
			_batchedJoinBlock = batchedJoinBlock;
			_sourceDebuggingInformation = batchedJoinBlock._source.GetDebuggingInformation();
		}
	}

	private readonly int _batchSize;

	private readonly BatchedJoinBlockTargetSharedResources _sharedResources;

	private readonly BatchedJoinBlockTarget<T1> _target1;

	private readonly BatchedJoinBlockTarget<T2> _target2;

	private readonly SourceCore<Tuple<IList<T1>, IList<T2>>> _source;

	/// <summary>Gets the size of the batches generated by this <see cref="T:System.Threading.Tasks.Dataflow.BatchedJoinBlock`2" />.</summary>
	/// <returns>The batch size.</returns>
	public int BatchSize => _batchSize;

	/// <summary>Gets a target that may be used to offer messages of the first type.</summary>
	/// <returns>The target.</returns>
	public ITargetBlock<T1> Target1 => _target1;

	/// <summary>Gets a target that may be used to offer messages of the second type.</summary>
	/// <returns>The target.</returns>
	public ITargetBlock<T2> Target2 => _target2;

	/// <summary>Gets the number of output items available to be received from this block.</summary>
	/// <returns>The number of output items.</returns>
	public int OutputCount => _source.OutputCount;

	/// <summary>Gets a <see cref="T:System.Threading.Tasks.Task" /> that represents the asynchronous operation and completion of the dataflow block.</summary>
	/// <returns>The task.</returns>
	public Task Completion => _source.Completion;

	private int OutputCountForDebugger => _source.GetDebuggingInformation().OutputCount;

	private object DebuggerDisplayContent => $"{Common.GetNameForDebugger(this, _source.DataflowBlockOptions)}, BatchSize = {BatchSize}, OutputCount = {OutputCountForDebugger}";

	object IDebuggerDisplay.Content => DebuggerDisplayContent;

	/// <summary>Initializes a new<see cref="T:System.Threading.Tasks.Dataflow.BatchedJoinBlock`2" /> with the specified configuration.</summary>
	/// <param name="batchSize">The number of items to group into a batch.</param>
	/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="batchSize" /> must be positive.</exception>
	public BatchedJoinBlock(int batchSize)
		: this(batchSize, GroupingDataflowBlockOptions.Default)
	{
	}

	/// <summary>Initializes a new <see cref="T:System.Threading.Tasks.Dataflow.BatchedJoinBlock`2" /> with the specified configuration.</summary>
	/// <param name="batchSize">The number of items to group into a batch.</param>
	/// <param name="dataflowBlockOptions">The options with which to configure this <see cref="T:System.Threading.Tasks.Dataflow.BatchedJoinBlock`2" />.</param>
	/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="batchSize" /> must be positive.</exception>
	/// <exception cref="T:System.ArgumentNullException">The <paramref name="dataflowBlockOptions" /> is null.</exception>
	public BatchedJoinBlock(int batchSize, GroupingDataflowBlockOptions dataflowBlockOptions)
	{
		if (batchSize < 1)
		{
			throw new ArgumentOutOfRangeException("batchSize", System.SR.ArgumentOutOfRange_GenericPositive);
		}
		if (dataflowBlockOptions == null)
		{
			throw new ArgumentNullException("dataflowBlockOptions");
		}
		if (!dataflowBlockOptions.Greedy)
		{
			throw new ArgumentException(System.SR.Argument_NonGreedyNotSupported, "dataflowBlockOptions");
		}
		if (dataflowBlockOptions.BoundedCapacity != -1)
		{
			throw new ArgumentException(System.SR.Argument_BoundedCapacityNotSupported, "dataflowBlockOptions");
		}
		_batchSize = batchSize;
		dataflowBlockOptions = dataflowBlockOptions.DefaultOrClone();
		_source = new SourceCore<Tuple<IList<T1>, IList<T2>>>(this, dataflowBlockOptions, delegate(ISourceBlock<Tuple<IList<T1>, IList<T2>>> owningSource)
		{
			((BatchedJoinBlock<T1, T2>)owningSource).CompleteEachTarget();
		});
		Action createBatchAction = delegate
		{
			if (_target1.Count > 0 || _target2.Count > 0)
			{
				_source.AddMessage(Tuple.Create(_target1.GetAndEmptyMessages(), _target2.GetAndEmptyMessages()));
			}
		};
		_sharedResources = new BatchedJoinBlockTargetSharedResources(batchSize, dataflowBlockOptions, createBatchAction, delegate
		{
			createBatchAction();
			_source.Complete();
		}, _source.AddException, Complete);
		_target1 = new BatchedJoinBlockTarget<T1>(_sharedResources);
		_target2 = new BatchedJoinBlockTarget<T2>(_sharedResources);
		_source.Completion.ContinueWith(delegate(Task completed, object state)
		{
			((IDataflowBlock)(BatchedJoinBlock<T1, T2>)state).Fault((Exception)completed.Exception);
		}, this, CancellationToken.None, Common.GetContinuationOptions() | TaskContinuationOptions.OnlyOnFaulted, TaskScheduler.Default);
		Common.WireCancellationToComplete(dataflowBlockOptions.CancellationToken, _source.Completion, delegate(object state, CancellationToken _)
		{
			((BatchedJoinBlock<T1, T2>)state).CompleteEachTarget();
		}, this);
		DataflowEtwProvider log = DataflowEtwProvider.Log;
		if (log.IsEnabled())
		{
			log.DataflowBlockCreated(this, dataflowBlockOptions);
		}
	}

	/// <summary>Links the <see cref="T:System.Threading.Tasks.Dataflow.ISourceBlock`1" /> to the specified <see cref="T:System.Threading.Tasks.Dataflow.ITargetBlock`1" />.</summary>
	/// <returns>An IDisposable that, upon calling Dispose, will unlink the source from the target.</returns>
	/// <param name="target">The <see cref="T:System.Threading.Tasks.Dataflow.ITargetBlock`1" /> to which to connect this source.</param>
	/// <param name="linkOptions">A <see cref="T:System.Threading.Tasks.Dataflow.DataflowLinkOptions" />  instance that configures the link.</param>
	/// <exception cref="T:System.ArgumentNullException">
	///   <paramref name="target" /> is null (Nothing in Visual Basic) or <paramref name="linkOptions" /> is null (Nothing in Visual Basic).</exception>
	public IDisposable LinkTo(ITargetBlock<Tuple<IList<T1>, IList<T2>>> target, DataflowLinkOptions linkOptions)
	{
		return _source.LinkTo(target, linkOptions);
	}

	/// <summary>Attempts to synchronously receive an available output item from the <see cref="T:System.Threading.Tasks.Dataflow.IReceivableSourceBlock`1" />.</summary>
	/// <returns>true if an item could be received; otherwise, false.</returns>
	/// <param name="filter">The predicate a value must successfully pass in order for it to be received. <paramref name="filter" /> may be null, in which case all items will pass.</param>
	/// <param name="item">The item received from the source.</param>
	public bool TryReceive(Predicate<Tuple<IList<T1>, IList<T2>>>? filter, [NotNullWhen(true)] out Tuple<IList<T1>, IList<T2>>? item)
	{
		return _source.TryReceive(filter, out item);
	}

	/// <summary>Attempts to synchronously receive all available items from the <see cref="T:System.Threading.Tasks.Dataflow.IReceivableSourceBlock`1" />.</summary>
	/// <returns>true if one or more items could be received; otherwise, false.</returns>
	/// <param name="items">The items received from the source.</param>
	public bool TryReceiveAll([NotNullWhen(true)] out IList<Tuple<IList<T1>, IList<T2>>>? items)
	{
		return _source.TryReceiveAll(out items);
	}

	/// <summary>Signals to the <see cref="T:System.Threading.Tasks.Dataflow.IDataflowBlock" /> that it should not accept nor produce any more messages nor consume any more postponed messages.</summary>
	public void Complete()
	{
		_target1.Complete();
		_target2.Complete();
	}

	/// <summary>Causes the <see cref="T:System.Threading.Tasks.Dataflow.IDataflowBlock" /> to complete in a <see cref="F:System.Threading.Tasks.TaskStatus.Faulted" /> state.</summary>
	/// <param name="exception">The <see cref="T:System.Exception" /> that caused the faulting.</param>
	/// <exception cref="T:System.ArgumentNullException">The <paramref name="exception" /> is null.</exception>
	void IDataflowBlock.Fault(Exception exception)
	{
		ArgumentNullException.ThrowIfNull(exception, "exception");
		lock (_sharedResources._incomingLock)
		{
			if (!_sharedResources._decliningPermanently)
			{
				_source.AddException(exception);
			}
		}
		Complete();
	}

	Tuple<IList<T1>, IList<T2>> ISourceBlock<Tuple<IList<T1>, IList<T2>>>.ConsumeMessage(DataflowMessageHeader messageHeader, ITargetBlock<Tuple<IList<T1>, IList<T2>>> target, out bool messageConsumed)
	{
		return _source.ConsumeMessage(messageHeader, target, out messageConsumed);
	}

	bool ISourceBlock<Tuple<IList<T1>, IList<T2>>>.ReserveMessage(DataflowMessageHeader messageHeader, ITargetBlock<Tuple<IList<T1>, IList<T2>>> target)
	{
		return _source.ReserveMessage(messageHeader, target);
	}

	void ISourceBlock<Tuple<IList<T1>, IList<T2>>>.ReleaseReservation(DataflowMessageHeader messageHeader, ITargetBlock<Tuple<IList<T1>, IList<T2>>> target)
	{
		_source.ReleaseReservation(messageHeader, target);
	}

	private void CompleteEachTarget()
	{
		_target1.Complete();
		_target2.Complete();
	}

	/// <summary>Returns a string that represents the formatted name of this <see cref="T:System.Threading.Tasks.Dataflow.IDataflowBlock" /> instance.</summary>
	/// <returns>A string that represents the formatted name of this <see cref="T:System.Threading.Tasks.Dataflow.IDataflowBlock" /> instance.</returns>
	public override string ToString()
	{
		return Common.GetNameForDebugger(this, _source.DataflowBlockOptions);
	}
}
/// <summary>Provides a dataflow block that batches a specified number of inputs of potentially differing types provided to one or more of its targets.</summary>
/// <typeparam name="T1">Specifies the type of data accepted by the block's first target.</typeparam>
/// <typeparam name="T2">Specifies the type of data accepted by the block's second target.</typeparam>
/// <typeparam name="T3">Specifies the type of data accepted by the block's third target.</typeparam>
[DebuggerDisplay("{DebuggerDisplayContent,nq}")]
[DebuggerTypeProxy(typeof(BatchedJoinBlock<, , >.DebugView))]
public sealed class BatchedJoinBlock<T1, T2, T3> : IReceivableSourceBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>>, ISourceBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>>, IDataflowBlock, IDebuggerDisplay
{
	private sealed class DebugView
	{
		private readonly BatchedJoinBlock<T1, T2, T3> _batchedJoinBlock;

		private readonly SourceCore<Tuple<IList<T1>, IList<T2>, IList<T3>>>.DebuggingInformation _sourceDebuggingInformation;

		public IEnumerable<Tuple<IList<T1>, IList<T2>, IList<T3>>> OutputQueue => _sourceDebuggingInformation.OutputQueue;

		public long BatchesCreated => _batchedJoinBlock._sharedResources._batchesCreated;

		public int RemainingItemsForBatch => _batchedJoinBlock._sharedResources._remainingItemsInBatch;

		public int BatchSize => _batchedJoinBlock._batchSize;

		public ITargetBlock<T1> Target1 => _batchedJoinBlock._target1;

		public ITargetBlock<T2> Target2 => _batchedJoinBlock._target2;

		public ITargetBlock<T3> Target3 => _batchedJoinBlock._target3;

		public Task TaskForOutputProcessing => _sourceDebuggingInformation.TaskForOutputProcessing;

		public GroupingDataflowBlockOptions DataflowBlockOptions => (GroupingDataflowBlockOptions)_sourceDebuggingInformation.DataflowBlockOptions;

		public bool IsCompleted => _sourceDebuggingInformation.IsCompleted;

		public int Id => Common.GetBlockId(_batchedJoinBlock);

		public TargetRegistry<Tuple<IList<T1>, IList<T2>, IList<T3>>> LinkedTargets => _sourceDebuggingInformation.LinkedTargets;

		public ITargetBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>> NextMessageReservedFor => _sourceDebuggingInformation.NextMessageReservedFor;

		public DebugView(BatchedJoinBlock<T1, T2, T3> batchedJoinBlock)
		{
			_sourceDebuggingInformation = batchedJoinBlock._source.GetDebuggingInformation();
			_batchedJoinBlock = batchedJoinBlock;
		}
	}

	private readonly int _batchSize;

	private readonly BatchedJoinBlockTargetSharedResources _sharedResources;

	private readonly BatchedJoinBlockTarget<T1> _target1;

	private readonly BatchedJoinBlockTarget<T2> _target2;

	private readonly BatchedJoinBlockTarget<T3> _target3;

	private readonly SourceCore<Tuple<IList<T1>, IList<T2>, IList<T3>>> _source;

	/// <summary>Gets the size of the batches generated by this <see cref="T:System.Threading.Tasks.Dataflow.BatchedJoinBlock`3" />.</summary>
	/// <returns>The batch size.</returns>
	public int BatchSize => _batchSize;

	/// <summary>Gets a target that may be used to offer messages of the first type.</summary>
	/// <returns>The target.</returns>
	public ITargetBlock<T1> Target1 => _target1;

	/// <summary>Gets a target that may be used to offer messages of the second type.</summary>
	/// <returns>The target.</returns>
	public ITargetBlock<T2> Target2 => _target2;

	/// <summary>Gets a target that may be used to offer messages of the third type.</summary>
	/// <returns>The target.</returns>
	public ITargetBlock<T3> Target3 => _target3;

	/// <summary>Gets the number of output items available to be received from this block.</summary>
	/// <returns>The number of output items.</returns>
	public int OutputCount => _source.OutputCount;

	/// <summary>Gets a <see cref="T:System.Threading.Tasks.Task" /> that represents the asynchronous operation and completion of the dataflow block.</summary>
	/// <returns>The task.</returns>
	public Task Completion => _source.Completion;

	private int OutputCountForDebugger => _source.GetDebuggingInformation().OutputCount;

	private object DebuggerDisplayContent => $"{Common.GetNameForDebugger(this, _source.DataflowBlockOptions)}, BatchSize = {BatchSize}, OutputCount = {OutputCountForDebugger}";

	object IDebuggerDisplay.Content => DebuggerDisplayContent;

	/// <summary>Initializes a new <see cref="T:System.Threading.Tasks.Dataflow.BatchedJoinBlock`3" /> with the specified configuration.</summary>
	/// <param name="batchSize">The number of items to group into a batch.</param>
	/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="batchSize" /> must be positive.</exception>
	public BatchedJoinBlock(int batchSize)
		: this(batchSize, GroupingDataflowBlockOptions.Default)
	{
	}

	/// <summary>Initializes a new <see cref="T:System.Threading.Tasks.Dataflow.BatchedJoinBlock`3" /> with the specified configuration.</summary>
	/// <param name="batchSize">The number of items to group into a batch.</param>
	/// <param name="dataflowBlockOptions">The options with which to configure this <see cref="T:System.Threading.Tasks.Dataflow.BatchedJoinBlock`2" />.</param>
	/// <exception cref="T:System.ArgumentOutOfRangeException">The <paramref name="batchSize" /> must be positive.</exception>
	/// <exception cref="T:System.ArgumentNullException">The <paramref name="dataflowBlockOptions" /> is null.</exception>
	public BatchedJoinBlock(int batchSize, GroupingDataflowBlockOptions dataflowBlockOptions)
	{
		if (batchSize < 1)
		{
			throw new ArgumentOutOfRangeException("batchSize", System.SR.ArgumentOutOfRange_GenericPositive);
		}
		if (dataflowBlockOptions == null)
		{
			throw new ArgumentNullException("dataflowBlockOptions");
		}
		if (!dataflowBlockOptions.Greedy || dataflowBlockOptions.BoundedCapacity != -1)
		{
			throw new ArgumentException(System.SR.Argument_NonGreedyNotSupported, "dataflowBlockOptions");
		}
		_batchSize = batchSize;
		dataflowBlockOptions = dataflowBlockOptions.DefaultOrClone();
		_source = new SourceCore<Tuple<IList<T1>, IList<T2>, IList<T3>>>(this, dataflowBlockOptions, delegate(ISourceBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>> owningSource)
		{
			((BatchedJoinBlock<T1, T2, T3>)owningSource).CompleteEachTarget();
		});
		Action createBatchAction = delegate
		{
			if (_target1.Count > 0 || _target2.Count > 0 || _target3.Count > 0)
			{
				_source.AddMessage(Tuple.Create(_target1.GetAndEmptyMessages(), _target2.GetAndEmptyMessages(), _target3.GetAndEmptyMessages()));
			}
		};
		_sharedResources = new BatchedJoinBlockTargetSharedResources(batchSize, dataflowBlockOptions, createBatchAction, delegate
		{
			createBatchAction();
			_source.Complete();
		}, _source.AddException, Complete);
		_target1 = new BatchedJoinBlockTarget<T1>(_sharedResources);
		_target2 = new BatchedJoinBlockTarget<T2>(_sharedResources);
		_target3 = new BatchedJoinBlockTarget<T3>(_sharedResources);
		_source.Completion.ContinueWith(delegate(Task completed, object state)
		{
			((IDataflowBlock)(BatchedJoinBlock<T1, T2, T3>)state).Fault((Exception)completed.Exception);
		}, this, CancellationToken.None, Common.GetContinuationOptions() | TaskContinuationOptions.OnlyOnFaulted, TaskScheduler.Default);
		Common.WireCancellationToComplete(dataflowBlockOptions.CancellationToken, _source.Completion, delegate(object state, CancellationToken _)
		{
			((BatchedJoinBlock<T1, T2, T3>)state).CompleteEachTarget();
		}, this);
		DataflowEtwProvider log = DataflowEtwProvider.Log;
		if (log.IsEnabled())
		{
			log.DataflowBlockCreated(this, dataflowBlockOptions);
		}
	}

	/// <summary>Links the <see cref="T:System.Threading.Tasks.Dataflow.ISourceBlock`1" /> to the specified <see cref="T:System.Threading.Tasks.Dataflow.ITargetBlock`1" />.</summary>
	/// <returns>An IDisposable that, upon calling Dispose, will unlink the source from the target.</returns>
	/// <param name="target">The <see cref="T:System.Threading.Tasks.Dataflow.ITargetBlock`1" /> to which to connect this source.</param>
	/// <param name="linkOptions">true if the source should unlink from the target after successfully propagating a single message; false to remain connected even after a single message has been propagated.</param>
	/// <exception cref="T:System.ArgumentNullException">
	///   <paramref name="target" /> is null (Nothing in Visual Basic) or <paramref name="linkOptions" /> is null (Nothing in Visual Basic).</exception>
	public IDisposable LinkTo(ITargetBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>> target, DataflowLinkOptions linkOptions)
	{
		return _source.LinkTo(target, linkOptions);
	}

	/// <summary>Attempts to synchronously receive an available output item from the <see cref="T:System.Threading.Tasks.Dataflow.IReceivableSourceBlock`1" />.</summary>
	/// <returns>true if an item could be received; otherwise, false.</returns>
	/// <param name="filter">The predicate a value must successfully pass in order for it to be received. <paramref name="filter" /> may be null in which case all items will pass.</param>
	/// <param name="item">The item received from the source.</param>
	public bool TryReceive(Predicate<Tuple<IList<T1>, IList<T2>, IList<T3>>>? filter, [NotNullWhen(true)] out Tuple<IList<T1>, IList<T2>, IList<T3>>? item)
	{
		return _source.TryReceive(filter, out item);
	}

	/// <summary>Attempts to synchronously receive all available items from the <see cref="T:System.Threading.Tasks.Dataflow.IReceivableSourceBlock`1" />.</summary>
	/// <returns>true if one or more items could be received; otherwise, false.</returns>
	/// <param name="items">The items received from the source.</param>
	public bool TryReceiveAll([NotNullWhen(true)] out IList<Tuple<IList<T1>, IList<T2>, IList<T3>>>? items)
	{
		return _source.TryReceiveAll(out items);
	}

	/// <summary>Signals to the <see cref="T:System.Threading.Tasks.Dataflow.IDataflowBlock" /> that it should not accept nor produce any more messages nor consume any more postponed messages.</summary>
	public void Complete()
	{
		_target1.Complete();
		_target2.Complete();
		_target3.Complete();
	}

	/// <summary>Causes the <see cref="T:System.Threading.Tasks.Dataflow.IDataflowBlock" /> to complete in a <see cref="F:System.Threading.Tasks.TaskStatus.Faulted" /> state.</summary>
	/// <param name="exception">The <see cref="T:System.Exception" /> that caused the faulting.</param>
	/// <exception cref="T:System.ArgumentNullException">The <paramref name="exception" /> is null.</exception>
	void IDataflowBlock.Fault(Exception exception)
	{
		ArgumentNullException.ThrowIfNull(exception, "exception");
		lock (_sharedResources._incomingLock)
		{
			if (!_sharedResources._decliningPermanently)
			{
				_source.AddException(exception);
			}
		}
		Complete();
	}

	Tuple<IList<T1>, IList<T2>, IList<T3>> ISourceBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>>.ConsumeMessage(DataflowMessageHeader messageHeader, ITargetBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>> target, out bool messageConsumed)
	{
		return _source.ConsumeMessage(messageHeader, target, out messageConsumed);
	}

	bool ISourceBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>>.ReserveMessage(DataflowMessageHeader messageHeader, ITargetBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>> target)
	{
		return _source.ReserveMessage(messageHeader, target);
	}

	void ISourceBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>>.ReleaseReservation(DataflowMessageHeader messageHeader, ITargetBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>> target)
	{
		_source.ReleaseReservation(messageHeader, target);
	}

	private void CompleteEachTarget()
	{
		_target1.Complete();
		_target2.Complete();
		_target3.Complete();
	}

	/// <summary>Returns a string that represents the formatted name of this <see cref="T:System.Threading.Tasks.Dataflow.IDataflowBlock" /> instance.</summary>
	/// <returns>A string that represents the formatted name of this <see cref="T:System.Threading.Tasks.Dataflow.IDataflowBlock" /> instance.</returns>
	public override string ToString()
	{
		return Common.GetNameForDebugger(this, _source.DataflowBlockOptions);
	}
}
