using System.Diagnostics;

namespace System.Threading.Tasks.Dataflow;

/// <summary>Provides options used to configure the processing performed by dataflow blocks that group together multiple messages. These are dataflow blocks such as <see cref="T:System.Threading.Tasks.Dataflow.JoinBlock`2" /> and <see cref="T:System.Threading.Tasks.Dataflow.BatchBlock`1" />.</summary>
[DebuggerDisplay("TaskScheduler = {TaskScheduler}, MaxMessagesPerTask = {MaxMessagesPerTask}, BoundedCapacity = {BoundedCapacity}, Greedy = {Greedy}, MaxNumberOfGroups = {MaxNumberOfGroups}")]
public class GroupingDataflowBlockOptions : DataflowBlockOptions
{
	internal new static readonly GroupingDataflowBlockOptions Default = new GroupingDataflowBlockOptions();

	private bool _greedy = true;

	private long _maxNumberOfGroups = -1L;

	/// <summary>Gets or sets the Boolean value to use to determine whether to greedily consume offered messages.</summary>
	/// <returns>true to greedily consume offered messages; otherwise, false.</returns>
	public bool Greedy
	{
		get
		{
			return _greedy;
		}
		set
		{
			_greedy = value;
		}
	}

	/// <summary>Gets or sets the maximum number of groups that should be generated by the block.</summary>
	/// <returns>The maximum number of groups.</returns>
	public long MaxNumberOfGroups
	{
		get
		{
			return _maxNumberOfGroups;
		}
		set
		{
			if (value <= 0 && value != -1)
			{
				throw new ArgumentOutOfRangeException("value");
			}
			_maxNumberOfGroups = value;
		}
	}

	internal long ActualMaxNumberOfGroups
	{
		get
		{
			if (_maxNumberOfGroups != -1)
			{
				return _maxNumberOfGroups;
			}
			return long.MaxValue;
		}
	}

	internal new GroupingDataflowBlockOptions DefaultOrClone()
	{
		if (this != Default)
		{
			return new GroupingDataflowBlockOptions
			{
				TaskScheduler = base.TaskScheduler,
				CancellationToken = base.CancellationToken,
				MaxMessagesPerTask = base.MaxMessagesPerTask,
				BoundedCapacity = base.BoundedCapacity,
				NameFormat = base.NameFormat,
				EnsureOrdered = base.EnsureOrdered,
				Greedy = Greedy,
				MaxNumberOfGroups = MaxNumberOfGroups
			};
		}
		return this;
	}

	/// <summary>Initializes a new <see cref="T:System.Threading.Tasks.Dataflow.GroupingDataflowBlockOptions" />.</summary>
	public GroupingDataflowBlockOptions()
	{
	}
}
