<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Defenders of the Last Colony</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFramework>net5.0-windows7.0</TargetFramework>
		<OutputType>WinExe</OutputType>
		<Platforms>x86;x64</Platforms>
		<PlatformTarget>x86</PlatformTarget>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
		<EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
		<StartupObject>Defenders.Program</StartupObject>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Content-References\FNA.Contents.csproj">
			<Private>True</Private>
			<CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="EasyStorage">
			<HintPath>EasyStorage.dll</HintPath>
			<Private>True</Private>
		</Reference>
		<Reference Include="Hammer">
			<HintPath>Hammer.dll</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Include="de/EasyStorage.resources.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="es/EasyStorage.resources.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="fr/EasyStorage.resources.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="it/EasyStorage.resources.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="ja/EasyStorage.resources.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="EasyStorage.Strings.ja.resx" />
		<EmbeddedResource Include="EasyStorage.Strings.resx" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Content\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>